-- ============================================================
-- Skema database LigaLestari — Neon (Postgres)
-- Dijalankan lewat `npm run db:migrate` (lihat db/migrate.mjs),
-- atau manual: psql "$DATABASE_URL" -f db/schema.sql
--
-- Aman diulang: seluruh objek dibuat ulang dari nol.
-- Keamanan: database hanya diakses server Nuxt lewat koneksi
-- terenkripsi (DATABASE_URL tidak pernah dikirim ke browser),
-- jadi tidak ada peran anon yang perlu dibatasi RLS.
-- ============================================================

drop table if exists profil, riwayat_tim, siswa, setoran, bukti_tanam,
  titik_tanam, notifikasi, badge, laporan_bulanan, laporan_spesies,
  event_liga, jenis_pohon, artikel, pengaturan, tim, musim cascade;

-- Sisa skema Supabase lama (digantikan tabel profil).
drop table if exists akun cascade;

-- ---------- Liga ----------

-- Konfigurasi musim berjalan (satu baris) + event yang sedang aktif.
create table musim (
  id int primary key default 1 check (id = 1),
  nama text not null,
  pekan int not null,
  total_pekan int not null,
  berakhir text not null,
  sisa_hari int not null,
  event_label text not null,
  event_nama text not null,
  event_sisa_hari int not null
);

-- Satu tim = satu kelas peserta liga.
create table tim (
  id text primary key,
  nama text not null,
  julukan text not null,
  emblem text not null,
  warna text not null,
  poin int not null default 0,
  kg int not null default 0,
  pohon int not null default 0,
  co2 int not null default 0,
  tren int not null default 0,
  poin_sampah int not null default 0,
  poin_pohon int not null default 0,
  jumlah_siswa int not null default 0,
  kode_gabung text unique,
  tahun_ajaran text not null default '2025/2026'
);

create table siswa (
  id bigint generated by default as identity primary key,
  kelas_id text not null references tim (id) on delete cascade,
  nama text not null,
  nis text not null,
  poin int not null default 0,
  peran text,
  level int not null default 1,
  nama_level text not null default 'Pemula Hijau',
  kg int not null default 0,
  pohon int not null default 0,
  persen_level int not null default 0,
  poin_ke_level_berikut int not null default 100
);

create index siswa_kelas_idx on siswa (kelas_id, poin desc);

-- Akun aplikasi. Sandi disimpan sebagai hash scrypt (nuxt-auth-utils);
-- teks polosnya tidak pernah tersimpan di mana pun.
create table profil (
  id bigint generated by default as identity primary key,
  pengguna text unique not null,
  nama text not null,
  peran text not null check (peran in ('siswa', 'admin')),
  sandi_hash text not null,
  kelas_id text references tim (id) on delete set null,
  siswa_id bigint references siswa (id) on delete set null,
  dibuat timestamptz not null default now()
);

create index profil_siswa_idx on profil (siswa_id);

-- ---------- Konten ----------

create table artikel (
  slug text primary key,
  judul text not null,
  kategori text not null check (kategori in ('sampah', 'pohon')),
  menit_baca int not null,
  ringkasan text not null,
  tanggal date not null,
  thumb_tag text not null,
  thumb_alt text not null,
  isi jsonb not null,    -- [{jenis:'judul'|'paragraf'|'poin', teks}]
  sumber jsonb not null  -- [teks, ...]
);

create table jenis_pohon (
  nama text primary key,
  latin text not null,
  serapan numeric not null, -- kg CO2 / pohon / tahun
  sumber text not null,
  warna text not null
);

create table titik_tanam (
  id bigint generated by default as identity primary key,
  kelas_id text not null references tim (id) on delete cascade,
  x numeric not null,
  y numeric not null,
  jumlah int not null,
  jenis_pohon text not null,
  co2 int not null,
  tanggal text not null,
  -- Foto dokumentasi yang diunggah siswa saat menanam (URL/path publik).
  foto text
);

create index titik_tanam_kelas_idx on titik_tanam (kelas_id);

-- ---------- Operasional admin ----------

create table event_liga (
  id bigint generated by default as identity primary key,
  nama text not null,
  jenis text not null check (jenis in ('sampah', 'pohon')),
  rate text not null,
  status text not null check (status in ('Aktif', 'Terjadwal', 'Selesai')),
  periode text not null,
  urutan int not null default 0
);

-- Enam kategori terpilah yang diakui liga — sama persis dengan
-- `KategoriSampah` di shared/types (satu sumber kebenaran tarif ada
-- di shared/data/kategori-sampah.ts).
create table setoran (
  id bigint generated by default as identity primary key,
  dibuat timestamptz not null default now(),
  waktu text not null, -- tampilan "HH.MM"
  kelas text not null,
  kategori text not null
    check (kategori in ('organik', 'kertas', 'plastik', 'kaca', 'logam', 'b3-ringan')),
  kg numeric not null check (kg > 0),
  poin int not null
);

create index setoran_dibuat_idx on setoran (dibuat desc);

create table bukti_tanam (
  id bigint generated by default as identity primary key,
  kelas_id text not null references tim (id) on delete cascade,
  pohon int not null,
  jenis_pohon text not null,
  co2 int not null,
  koordinat text not null,
  lokasi text not null,
  waktu text not null,
  keputusan text check (keputusan in ('disetujui', 'ditolak'))
);

-- ---------- Dasbor siswa ----------

create table notifikasi (
  id bigint generated by default as identity primary key,
  judul text not null,
  isi text not null,
  waktu text not null,
  tag text not null,
  warna text not null,
  ikon text not null,
  belum_dibaca boolean not null default false,
  urutan int not null default 0
);

create table badge (
  id bigint generated by default as identity primary key,
  nama text not null,
  syarat text not null,
  dapat boolean not null default false,
  urutan int not null default 0
);

create table riwayat_tim (
  id bigint generated by default as identity primary key,
  kelas_id text not null references tim (id) on delete cascade,
  teks text not null,
  waktu text not null,
  poin text,
  warna text not null,
  urutan int not null default 0
);

create index riwayat_tim_kelas_idx on riwayat_tim (kelas_id, urutan);

-- ---------- Laporan ----------

create table laporan_bulanan (
  bulan text primary key,
  kg int not null,
  urutan int not null default 0
);

create table laporan_spesies (
  nama text primary key,
  jumlah int not null,
  co2 int not null,
  persen int not null,
  warna text not null,
  urutan int not null default 0
);

-- ---------- Pengaturan ----------

-- Penyimpanan kunci-nilai untuk setelan yang diubah admin,
-- mis. `lokasi_sekolah` = {"lat":…,"lng":…,"zoom":…}.
create table pengaturan (
  kunci text primary key,
  nilai jsonb not null,
  diubah timestamptz not null default now()
);
